name: Clojure CI

on:
  push:
    branches: [ ci/test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run ClojureScript tests
      run: clojure -Mtest-cljs
    - name: run Clojure tests
      run: clojure -Mtest-clj
