name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@5.1
      with:
        cli: 1.10.1.693
        lein: 2.9.1
    - name: run ClojureScript tests
      run: clojure -Mtest-cljs
    - name: run Clojure tests
      run: clojure -Mtest-clj
